### ISSUE TITLE
Error: cannot find module '../package,json'

### ISSUE THREAD

**Issue by jdh0139** [solid/node-solid-server#604] opened 2017-09-17 23:33 UTC
1. os: Linux, Ubuntu 16.04.3 LTS
2. node: 6.11.3
    npm: 3.10.10
3. solid server install command.
    sudo npm install -g solid-server
4. The log given by the failure.
jdh0139@jdh0139-VirtualBox:~$ solid init
module.js:471
    throw err;
    ^
Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getVersion (/usr/lib/node_modules/solid-server/bin/lib/cli.js:24:25)
    at startCli (/usr/lib/node_modules/solid-server/bin/lib/cli.js:7:19)
    at Object.<anonymous> (/usr/lib/node_modules/solid-server/bin/solid:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by RubenVerborgh** [comment] 2017-09-18 15:43
Tried the same steps (with Node 8) and couldn't reproduce.

**Comment by dmitrizagidulin** [comment] 2017-09-18 15:58
I suspect this has to do with a global install of ldnode. So line 24 in cli.js is breaking -- it likely needs to use path.join() instead of `../`

**Comment by melvincarvalho** [comment] 2018-01-10 04:44
#606 has been merged and should fix this.  Please reopen if this issue persists.

**Closed by melvincarvalho** 2018-01-10 04:44 UTC
