### ISSUE TITLE
Root directory for warp w/solid specified as parent, but becomes child with dns name

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#460] opened 2016-11-30 18:49 UTC
I have a root directory in config.json specified as /opt/solid in /opt/solid. I have port number yourport specified in config.json. I have a child directory example.yourdomain.net . 

Warp (https://linkeddata.github.io/warp/) is serving the contents of the folder example.yourdomain.net from the URL https://example.yourdomain.net:yourport . 

config.json :

{                                                                                                                                              
  "root": "/opt/testone-solid/",                                                                                                               
  "port": "8445",                                                                                                                              
  "webid": true,                                                                                                                               
  "auth": "tls",                                                                                                                               
  "sslKey": "/.../privkey.pem",                                                                     
  "sslCert": "/../fullchain.pem",                                                                  
  "idp": true,                                                                                                                                 
  "fileBrowser": "https://linkeddata.github.io/warp/#/list/",                                                                                  
  "dataBrowser": true,                                                                                                                         
  "strictOrigin": false,                                                                                                                       
  "apiApps": "/opt/testone-solid/api/apps"                                                                                                     
} 

testone-solid (aka solid) -v output:

   solid:idp Account on hebegb.homeunix.net is not available / +21s
  solid:authentication Identified user: https://bshambaugh.databox.me/profile/card#me +331ms
  solid:index Looking for index in / +1ms
  solid:ACL Can https://bshambaugh.databox.me/profile/card#me Read https://hebegb.homeunix.net:8445/? +2ms
  solid:ACL Check if acl exist: https://hebegb.homeunix.net:8445/.acl +1ms
  solid:ACL Read access permitted to https://bshambaugh.databox.me/profile/card#me +50ms
  solid:ACL ACL policy found +1ms
  solid:get / on hebegb.homeunix.net +0ms
  solid:handlers GET -- Reading directory +5ms
  solid:handlers Files in directory: .acl,bshamdataboxmeprog.ttl,test +0ms
  solid:idp Account on hebegb.homeunix.net is not available / +786ms
  solid:authentication User: https://bshambaugh.databox.me/profile/card#me +1ms
  solid:ACL Can https://bshambaugh.databox.me/profile/card#me Read https://hebegb.homeunix.net:8445/? +0ms
  solid:ACL Check if acl exist: https://hebegb.homeunix.net:8445/.acl +1ms
  solid:ACL Read access permitted to https://bshambaugh.databox.me/profile/card#me +40ms
  solid:ACL ACL policy found +0ms
  solid:get / on hebegb.homeunix.net +0ms
  solid:handlers GET -- Reading directory +2ms
  solid:handlers Files in directory: .acl,bshamdataboxmeprog.ttl,test +1ms
  solid:get no translation text/turtle +14ms

**Comment by dmitrizagidulin** [comment] 2016-12-15 19:38
@bshambaugh Thanks for reporting. I'm not quite clear on what the issue is. What did you expect to happen, and what is happening instead?

**Comment by dmitrizagidulin** [comment] 2017-03-13 19:13
Closing this - feel free to reopen if you have further questions.

**Closed by dmitrizagidulin** 2017-03-13 19:13 UTC
