### ISSUE TITLE
Update OPTIONS, Allow, Accept-*

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#931] opened 2018-11-13 17:31 UTC
re:
```
curl -iX OPTIONS https://csarven.solid.community/

Vary: Accept, Authorization, Origin
Access-Control-Allow-Methods: OPTIONS,HEAD,GET,PATCH,POST,PUT,DELETE
Allow: GET,HEAD
Accept-Patch: application/sparql-update
````

* `Allow` should include what's really "allowed" eg. `OPTIONS` is a good start.
* If `Accept-Patch` is of any indication, add `PATCH` to `Allow`.
* If `PUT, POST` are also allowed add to `Allow`, and would be good to include `Accept-Put` and `Accept-Post` respectively (note: `Accept-Put` is not really spec'd/standardised but just completeness sake)

Just to be clear, that's for a public resource. I understand that `GET`, `HEAD`, and `OPTIONS` may be the only methods allowed, then `Accept-Patch` probably shouldn't be advertised. No major harm but still. Note different treatment to https://csarven.solid.community/public/ , which appears to be correct (authenticated).

Aside: There may have been a special case for the storage root (I recall some people having issues with overwriting their homepage or whatever), so perhaps that's why `PATCH` is not listed there now (even if authenticated if I'm not mistaken). I don't see why `PATCH` would be allowed but not `PUT` or `POST`, and others on storage root, but ok.

**Comment by kidehen** [comment] 2018-11-13 17:35
@RubenVerborgh ,

Your thoughts on this matter? Fundamentally, we need to sort this out so that the following dokie.li features are demonstrable against a Solid Pod:

1. Reviews  Storage
2. Activities Viewing 

/cc @csarven

**Comment by RubenVerborgh** [comment] 2018-11-13 19:56
I'm trying to gauge the urgency of this issue. I get the eventual necessity, but what is broken right now that will be fixed when we do this?

There are more urgent blockers for dokieli, notably #661 (which is currently scheduled with a higher priority).

We have a limited team of developers, an internal deadline of November for v5.0, and more issues than this team can tackle by that date. So it's a matter of the right prioritization.

**Comment by dmitrizagidulin** [comment] 2018-11-13 20:36
@csarven Is this functionality not covered by the `WAC-Allow` header?

**Comment by kidehen** [comment] 2018-11-13 20:37
@RubenVerborgh,

What's broken right now is the basis of this issue. To reiterate, the following dokie.li functionality is unusable with NSS instance hosted Solid Pod:

1. Reviews Storage
2. Activity Tracking on a Document Reviewed by various folks identified by their respective WebIDs.

Fixing this problem makes the functionality in question usable and demonstrable i.e., powerful end-user app for demonstrating virtues of loosely-coupling:

1. Identity
2. Identification 
3. Authentication
4. Authorization
5. Storage 

Fundamentally, this is yet another killer-demo regarding how Solid enables a Read-Write Web without implicit Data Silos and end-user privacy compromise :)

**Comment by RubenVerborgh** [comment] 2018-11-13 20:38
But is #931 the reason why 1 and 2 are broken? I think the reason is #661.

**Comment by kidehen** [comment] 2018-11-14 01:45
@RubenVerborgh,

The issue is simply a case of dokie.li being able to discern the fact that RDF-Turtle is preferred by the Solid Pod deployed via NSS. 

If the correct metadata is returned via HTTP response headers dokie.li can make accurate deductions.

I hope this clarifies the issue at hand  so that we can move forward on this matter. Right now, we have a quite artificial hold-up that is blocking demonstration of the complete repetoire of capabilities that dokie.li brings to the table.

**Comment by csarven** [comment] 2018-11-14 09:41
Hang on folks. There sems to be some miscommunication here. Allow me try to clarify :)

The original issue is not related to 661/662, and it is not specific to dokieli either. It is something that NSS should do properly for `OPTIONS` requests - unless there are some undocumented heuristics in place for special treatment of `/`.

dokieli is first checking what the server is capable of and prefers through `OPTIONS`, if relevant (eg. `Accept-Post` and one of the mimetypes dokieli can handle) information is not found, it proceeds to do its LDN and WAP (which are JSON-LD based) out of the box. dokieli is fully capable of sending the payload in Turtle, JSON-LD, and HTML+RDFa. It just wants to know which methods it allows and mimetypes it prefers. At the moment it is looking out for information relevant for `POST` because the interactions around LDN and WAP use it. But, if `POST` is not possible to that target, that's okay too. The client should be able to see if `PUT` or `PATCH` are allowed for instance. At the moment, that doesn't appear to be the case either - `Accept-Patch` sort of hints that is possible what's intended but, to be specific, it only says what it prefers for `PATCH`. dokieli can send a `PATCH` too, so I suggest to at least include that in the `Allow` for starters.

So:

1) If agent is authenticated, shouldn't `OPTIONS` return something like `Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE` at `/`?
2) If `Accept-Post` or maybe even `Accept-Put` is possible, they should be included. We can put `Accept-Put` aside for now even as no one is really using that - although dokieli is prepared to do that - and will do (minor, unrelated to the core of the issue)

I understand that there may be good reasons for why storage `/` returns `Allow: GET, HEAD`, `Accept-Patch: application/sparql-update`, but apparently fine for another container eg `/public/`. That's part of the investigation.

Note that, dokieli happens to not find what it is looking for at `/` and ends up falling back to JSON-LD `POST` - I actually think dokieli shouldn't follow through in this case - and NSS seems to be okay with it (when the dokieli browser extension is used, and sending to `pim:storage` location), 201 Created, and 200 on the Location.

Did I add more confusion or make it clear? Let's put dokieli aside for now and doublecheck what the server should be doing.

Aside: yes, 661/662 are still quite important for dokieli but that is a different matter eg. 'Save'/'Save As' operations for HTML+RDFa articles use `PUT` (and the user names the target... and we don't want ugly `.html`). So, LDN/WAP expect the server to operate with JSON-LD, so this HTML stuff between dokieli and NSS is not relevant. dokieli has been doing fine with whatever non-HTML+RDFa NSS prefers through `OPTIONS`.

**Comment by kjetilk** [comment] 2018-11-14 10:44
Right, so yeah, I figured these issues were rather separate. Just trying to find what to prioritize.

Anyway, on the topic of `Allow`, I have never fully understood what solid tries to achieve with it. It seems to me it is a adding it rather [indiscriminately](https://github.com/solid/node-solid-server/blob/master/lib/create-app.js#L149), i.e. not what you can do with a resource, but what you could do if everything was just right, authn and authz and all that...  :-)

This looks to me to create a situation where you can't really rely on it, and quite a lot of logic around it would be needed to improve that. Is that part of the problem, @csarven , is it orthogonal to it, or am I just wrong in how Solid works?

**Comment by csarven** [comment] 2018-11-14 11:14
Identify and resolve the diff between `/` and eg `/public/`.

Needless to say, the server has to be consistently accurate, otherwise, clients are going to be built arbitrarily (out of "spec") because the server has arbitrary behaviour - at least in this particular case.

I have no comment or direct influence on prioritization of things. Just raising issues/QA stuff as usual that appears to require closer inspection or further development. IMO, the set of interactions that kickoff from `OPTIONS` are vital for improving interop because 1) there are existing standards that clients need to pick through, conform to, and concert with capable servers, and 2) closing gaps on what's unspecified with reliable fallbacks.

**Comment by RubenVerborgh** [comment] 2018-11-14 11:30
> * If agent is authenticated, shouldn't `OPTIONS` return something like `Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE` at `/`?

Yes. https://github.com/solid/node-solid-server/issues/934

> * If `Accept-Post` or maybe even `Accept-Put` is possible, they should be included.

They are just `*` though; or perhaps with a preference for Turtle if that is allowed. https://github.com/solid/node-solid-server/issues/935

Let's follow up in the above two separate issues.

**Closed by RubenVerborgh** 2018-11-14 11:30 UTC
Labels: inrupt-planning

**Comment by kidehen** [comment] 2018-11-14 12:04
@RubenVerborgh ,

> I love the "just works" experience as much as you do, and dokieli is one of the greatest demonstrators of decentralized Linked Data on the Web. But it's important that we fix things the right way. Shortcuts have been taken in the past, resulting in the difficult-to-maintain NSS codebase we currently have. Implementing the above headers would make things work in the short term, but they are not the right solution in the long term. Now that we have several "just works" experiences, it's important to shift focus to a long-term "keeps on working" experience IMHO.

But you are kinda misunderstanding my intentions and how I work. 

Please note:
* I am not a fan of shortcut hacks.  
* I try my best to get conflicts resolved between parties especially problems that are riddle-like in nature. 

I pushed this thread because I see and sense unecessary inertia, especially as dokie.li and Solid aren't tools that were created in the last few months --  these efforts have years behind them, and they should work much better than they do currently i.e., they should be clear working examples of the core value proposition espoused by the Solid Project.

**Comment by RubenVerborgh** [comment] 2018-11-14 12:08
>     * I am not a fan of shortcut hacks.

Apologies, I certainly did not mean to imply that. I know you favor good work.

What I meant to say is that, in this context and in my opinion, changing the Accept headers to say Turtle would be a shortcut, because it is not the truth.

> I see and sense unecessary inertia

Rest assured this is not how _we_ work 🙂
The number of issues is simply larger than the number of available hands. We're doing the best we can.

**Comment by kidehen** [comment] 2018-11-14 12:13
@RubenVerborgh ,

Here is what I meant to state and say:
NSS should use response metadata to inform user agents (e.g., dokie.li) about its preferences. That's it. 

What I describe above isn't happening. Thus, the only way for dokie.li to work properly with NSS is to drop down from good deductive pattern to a hack. 

This is an example of what I call a problem that's riddle-like in nature :) 

/cc @csarven

**Comment by RubenVerborgh** [comment] 2018-11-14 12:15
> NSS should use response metadata to inform user agents (e.g., dokie.li) about its preferences. That's it.

Check, thanks, following up on the two kinds of metadata in #934 and #935.

**Comment by kjetilk** [comment] 2018-11-14 12:17
> NSS should use response metadata to inform user agents (e.g., dokie.li) about its preferences. That's it.

Very, very much agreed. HATEOAS and all that. :-) I hope we get the chance to make this right soon.

**Comment by kjetilk** [comment] 2018-11-14 14:05
It does, thanks a lot, @dmitrizagidulin !

**Comment by csarven** [comment] 2018-11-14 14:05
@dmitrizagidulin The semantics of `Allow` is for a given resource, not a general announcement for servers capabilities (possibly for "all resources"): https://tools.ietf.org/html/rfc7231#section-7.4.1 . So, the server should signal what it really can for resource in question.

I think `WAC-Allow` is orthogonal. It doesn't (and shouldn't) override `Allow`.

**Comment by RubenVerborgh** [comment] 2018-11-14 14:06
Indeed, please see #934 and #935, which have all of this info 🙂
