### ISSUE TITLE
Cannot register account ("Account already exists")

### ISSUE THREAD

**Issue by angelo-v** [solid/node-solid-server#1029] opened 2018-12-15 19:52 UTC
Solid Server Versions:
* **5.0.0-beta.2**
* **5.0.0-beta.3**
* **5.0.0-beta.4**

*Expected Behaviour*: After setting up a solid server it should be possible to register an account

*Actual Behaviour*: When trying to register any account by submitting the registration form, the following error occurs: "Account already exists"

*Steps to reproduce*:

1. Visit https://angelo.veltens.org or set up your own solid-server on version 5.0.0-beta.3
2. Click `Register`
3. Fill out the registration form
4. Click `Submit`
5. See the mentioned error message on top of the page

**Comment by RubenVerborgh** [comment] 2018-12-15 19:53
Are you in multiuser mode?

**Comment by angelo-v** [comment] 2018-12-15 19:57
Since I did not enable it explicitly I guess not

**Comment by angelo-v** [comment] 2018-12-15 20:10
This is the form data that is transmitted to `api/accounts/new`:

```
username: solid-demo
password: *******
repeat_password: *******
name: solid-demo
email: me@mail.example
externalWebId: 
returnToUrl: 
response_type: 
display: 
scope: 
client_id: 
redirect_uri: 
state: 
nonce: 
request: 
```
Is it correct, that the latter params are all empty?

**Comment by angelo-v** [comment] 2018-12-15 20:31
Unfortunately the solid-server logs are quite silent... It's hard to find out what is going on. Is there some verbose mode or something?

**Comment by kjetilk** [comment] 2018-12-16 00:49
Sorry, I want to introduce a multi-level logger for exactly these occasions, but we haven't gotten to that yet. I'll try to see if I can reproduce the behaviour when getting back to work on Monday.

**Comment by kjetilk** [comment] 2018-12-18 13:56
> Unfortunately the solid-server logs are quite silent... It's hard to find out what is going on. Is there some verbose mode or something?

Actually, up to recently, I had verbose output with no further ado, but for some reason, I now need to set an environment variable, e.g.
```bash
export DEBUG=solid:*
```

does that improve the logging situation for you, @angelo-v ?

**Comment by angelo-v** [comment] 2018-12-18 15:53
Thanks, I tried that already, but didn't help. If you say it should, I will try again, to be sure I had no typo or something

**Comment by angelo-v** [comment] 2018-12-18 15:58
Ok, got it working, but doesn't help that much:
```
 solid:accounts Canceling account creation, https://angelo.veltens.org/profile/card#me already exists 
```

**Comment by megoth** [comment] 2018-12-18 15:58
I've been able to reproduce this bug (not being able to create accounts when server is set to singleuser; I'll look into this when I have time.

**Comment by kjetilk** [comment] 2018-12-18 21:40
So, @dmitrizagidulin , @megoth and I had a meeting to survey outstanding issues, and this turned out to be the most important regression that we've had so far. 

It has surfaced because the previous code checked to see if a root `.acl` existed to see if a user existed, but per the spec, the root `.acl` must always exist, so to make sure it does, we added it, and therefore introduced this problem as a side effect. 

But we have a plan! So, just to say, great testing! It is very valuable!

**Comment by angelo-v** [comment] 2018-12-25 17:46
Great that you have found the cause! Nice work, enjoy the holidays

**Comment by kjetilk** [comment] 2019-01-07 10:05
Are you available to look at this @joachimvh ?

**Comment by joachimvh** [comment] 2019-01-08 13:23
@kjetilk I'll look at it tomorrow

**Comment by joachimvh** [comment] 2019-01-10 08:11
@kjetilk do you have a config file on which this problem occurs? Because I can't seem to reproduce this problem on a clean install with `"multiuser": false` (user registration works for me there)

**Comment by kjetilk** [comment] 2019-01-10 14:58
@joachimvh have you checked out the `release/v5.0.0` branch?

**Comment by kjetilk** [comment] 2019-01-16 15:36
I think we have it fixed now, I'll look into releasing a new beta tonight.

**Closed by kjetilk** 2019-01-16 15:36 UTC
Labels: bug, inrupt-sprint
