### ISSUE TITLE
Path must be a string? Received 'undefined'

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#421] opened 2016-07-25 21:42 UTC
```
  solid:get /inbox/sparqlines-sparql-to-sparkline/ on linkedresearch.org +0ms
  solid:handlers GET -- Reading directory +5ms
  solid:handlers Files in directory:  +1ms
  solid:get no translation text/turtle +1ms
  solid:authentication No client certificate found in the request. Did the user click on a cert? +57s
  solid:ACL Can an agent Read https://linkedresearch.org/inbox/sparqlines-sparql-to-sparkline/? +1ms
  solid:ACL Check if acl exist: https://linkedresearch.org/inbox/sparqlines-sparql-to-sparkline/.acl +0ms
  solid:ACL Error: HTTPError: Can't read file +1ms
  solid:ACL Check if acl exist: https://linkedresearch.org/inbox/.acl +0ms
  solid:ACL Found policies in https://linkedresearch.org/inbox/.acl +2ms
  solid:ACL Checking for accessType:defaultForNew +0ms
  solid:ACL Inspect agentClass +0ms
  solid:ACL Checking for accessType:defaultForNew +1ms
  solid:ACL Inspect agentClass +0ms
  solid:ACL Found agentClass policy +0ms
  solid:ACL Read allowed access as FOAF agent +0ms
  solid:ACL ACL policy found +0ms
  solid:get /inbox/sparqlines-sparql-to-sparkline/ on linkedresearch.org +1ms
  solid:handlers GET -- Reading directory +0ms
  solid:handlers Files in directory:  +1ms
  solid:get no translation text/turtle +0ms
  solid:authentication No client certificate found in the request. Did the user click on a cert? +4m
  solid:server Error page because of Path must be a string. Received undefined +6ms
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/usr/local/lib/node_modules/solid-server/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:566:10)
    at writeend (/usr/local/lib/node_modules/solid-server/node_modules/express-session/index.js:257:22)
    at Immediate.onsave [as _onImmediate] (/usr/local/lib/node_modules/solid-server/node_modules/express-session/index.js:325:11)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by melvincarvalho** [comment] 2016-09-06 17:39
seeAlso : https://gitter.im/solid/node-solid-server?at=57ceee3377c1b70d7fedb80b

**Comment by dmitrizagidulin** [comment] 2016-12-07 21:57
Need more info on this to reproduce: what url are you trying to get. and are you logged in via webid-tls etc? and is it an access-controlled resource

**Comment by csarven** [comment] 2016-12-09 18:08
When the `On-Behalf-Of` header is sent with length > 0, it crashes the server.

**Comment by kidehen** [comment] 2016-12-09 18:18
@dmitrizagidulin -- Custom Headers are a fundamental part of HTTP. Thus, one shouldn't expect a  major fault  when those kinds of headers are encountered by an HTTP server.

**Comment by dmitrizagidulin** [comment] 2017-01-09 17:02
This is a duplicate of issue #473, closing.

**Closed by dmitrizagidulin** 2017-01-09 17:02 UTC
Labels: bug
