### ISSUE TITLE
How do people end up with a login subdomain? (It breaks OIDC issuer.)

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#941] opened 2018-11-16 13:43 UTC
@mguiral in https://github.com/solid/solid-cli/issues/4 ended up with a login subdomain. How did this happen, is that the default now?

**Comment by dmitrizagidulin** [comment] 2018-11-16 13:54
That’s really weird. I can’t imagine by what mechanism it would be the default! Will look.

**Comment by megoth** [comment] 2018-11-16 13:57
This should've been stopped by the blacklist-functionality, and login is on [the blacklist](https://github.com/marteinn/The-Big-Username-Blacklist/blob/master/list.txt).

Perhaps we haven't enforced the removal of usernames before the blacklist was put in place? Or perhaps the blacklist isn't working as intended... (I do not hope this is the case)?

**Comment by megoth** [comment] 2018-11-16 13:57
The PR for the blacklist is https://github.com/solid/node-solid-server/pull/893

**Comment by kjetilk** [comment] 2018-11-16 14:04
This was should have been in the 4.3.0 release, but perhaps the servers haven't been upgraded?

**Comment by kjetilk** [comment] 2018-11-16 14:13
Oh, reading on gitter, this doesn't seem to be about the blacklist, and not about our servers...

There's something creating that login subdomain... A bug?

**Comment by mguiral** [comment] 2018-11-16 14:47
After some investigations, i have on old .db folder with wrong provider.json configuration file. So i remove it but the page https://repo1.samy-poc.org/common/popup.html redirected me to https://login.repo1.samy-poc.org/login when i click on "Log in with repo1.samy-poc.org" button and now i have an unauthorized message.

Hope that helps

**Comment by mguiral** [comment] 2018-11-16 14:51
Ok now it's working. So i just have to delete the .db folder.
Thanks a lot for your time

**Comment by kjetilk** [comment] 2018-11-16 14:52
OK, great! However, could there have been a bug here that caused it to create a login host to begin with?

**Comment by mguiral** [comment] 2018-11-16 14:55
I think it will be great to delete .db folder when new solid init command line is running

**Comment by mguiral** [comment] 2018-11-16 15:03
You can close it

**Closed** 2018-11-16 16:06 UTC
Labels: question, triage
