### ISSUE TITLE
Unable to log in after upgrade

### ISSUE THREAD

**Issue by maxolasersquad** [solid/node-solid-server#1357] opened 2019-11-14 21:48 UTC
After upgrading node-solid-server I cannot log in. I get the message "No user found for that username". If I try to register the user anew I get "Account already exists".

**Comment by mikeadams1** [comment] 2019-11-16 10:20
@maxolasersquad What is the username you were trying to sign in on and what domain ie. inrupt. solid community?

**Comment by maxolasersquad** [comment] 2019-11-16 13:02
Username: david
Domain: solid.baucum.me

**Comment by mikeadams1** [comment] 2019-11-16 15:00
cant seem to access your site at all, seemed to work for a moment and then quit, maybe put your question up on solid-data-browser/chat

**Comment by jaxoncreed** [comment] 2019-11-18 20:05
Hmm I am unable to reproduce this error. Do you have access to the filesystem on your local deployment? You could reset your server by backing up information from the `/data` folder. Then delete the `.db` and `data` folders. Create a new account and transfer the backed up data back in.

**Comment by maxolasersquad** [comment] 2019-11-18 23:31
The site is https://solid.baucum.me/ It should be accessible.

I backed up and delete `.db.` and `data`. After trying to register I get `Error in put() - collection "users" does not exist`. After a second try the error goes back to `Account already exists`. The `.db` files was not automatically recreated.

**Comment by bourgeoa** [comment] 2019-11-19 09:40
Can you share your config file

**Comment by maxolasersquad** [comment] 2019-11-19 14:27
I use nginx to proxy requests on solid.baucum.me:443 to localhost:8443

```json
{
  "root": "/home/solid/data",
  "port": "8443",
  "serverUri": "https://solid.baucum.me",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "/home/solid/privkey.pem",
  "sslCert": "/home/solid/fullchain.pem",
  "multiuser": true,
  "supportEmail": "david@baucum.me",
  "email": {
    "host": "no",
    "port": "587",
    "secure": true,
    "auth": {
      "user": "not",
      "pass": "nope"
    }
  },
  "server": {
    "name": "Baucum",
    "description": "",
    "logo": ""
  }
}
```

**Comment by jaxoncreed** [comment] 2019-11-19 14:40
Did you restart Node Solid Server after deleting and restoring the backup? Folders are created on startup if they don't exist.

**Comment by bourgeoa** [comment] 2019-11-19 15:06
By memory your config.json seems wrong : 
`serverUri` should be : 
"serverUri": "https://solid.baucum.me:8443",

And you should nginx proxy : 
from `https://solid.baucum.me:443`
to `https://solid.baucum.me:8443`

That is what I am doing

Your `email` parameters are wrong
I don't remember using `server`

**Comment by jaxoncreed** [comment] 2019-11-22 17:14
@maxolasersquad Tell me if @bourgeoa 's suggestions worked for you.

I'm closing this for now, will reopen if you're still experiencing trouble.

**Closed by jaxoncreed** 2019-11-22 17:14 UTC

**Comment by maxolasersquad** [comment] 2019-11-27 01:38
Sorry. I'm not sure why it started happening now, but I was running into an issue with how my wildcard and root cert were configured in Nginx. I've straightened that up and was now able to register my user anew. Since I hadn't really used my solid server for anything it is nothing for me to just start from scratch. Thank you everyone who chimed in.
