### ISSUE TITLE
Add an Origin we control as trusted

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#738] opened 2018-08-06 23:51 UTC
@timbl said:

> Concluded to keep a long story short that 5.0.0 should run with every data browser running not in the  some origin as the data, but in a single trusted origin we control. Change the server so that it only gives the CORS origin-echo response for a specfic domain like apps.solid.org

**Comment by RubenVerborgh** [comment] 2018-08-08 12:07
Duplicate of #741.

**Closed by RubenVerborgh** 2018-08-08 12:07 UTC
