### ISSUE TITLE
Possibly add file extension when adding a POST

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#445] opened 2016-09-24 15:55 UTC
Raised by @timbl 

From gitter chat here:

https://gitter.im/linkedresearch/chat?at=57e64fd8240a335f12e881d8

> It should have been stored as 33560d70-81da-11e6-8400-5f305f4cc319$.jsonld then
> or else of course you could make things easier in he meantime and send a name which ends in .jsonld
> until the srever is fixed to add the extension
> Oh hang on that was generated by a POST with no slug?
> In that case maybe another issue with server - if generating a new id in a POST then add the right extension
> I have to go to the airport - could someone add an issue to the server about adding a file extension when something created and the server makes up a random URI?

**Comment by csarven** [comment] 2016-09-24 22:27
I think this issue is a duplicate of https://github.com/solid/node-solid-server/issues/413

**Comment by dmitrizagidulin** [comment] 2016-12-13 16:49
Closing as duplicate of [#275: Persist Content-Type of resources without file extensions](https://github.com/solid/node-solid-server/issues/275)

**Closed by dmitrizagidulin** 2016-12-13 16:49 UTC
