### ISSUE TITLE
'Delete Account' goes to wrong URL

### ISSUE THREAD

**Issue by kevin-howard-jd** [solid/node-solid-server#1250] opened 2019-06-27 13:31 UTC
When attempting to delete an existing Pod by clicking the 'Delete Account' button on the 'Solid Home' page, I am redirected to a URL https://_WebID_._PodProvider_/account/delete and am shown a page:

**No permission to access this resource**
You are currently logged in as https://_WebID_._PodProvider_/profile/card#me, but do not have permission to access https://_WebID_._PodProvider_/account/delete/.

The URL should be https://_PodProvider_/account/delete/. For example, https://inrupt.net/account/delete.

# To Replicate
1. Log into a Solid Pod.
2. Display the 'Solid Home' page.
3. Click the 'Delete Account' button.

# Expected Behaviour
1. Redirected to https://_PodProvider_/account/delete/ to allow Account name to be entered.

# Actual Behaviour
1. Redirected to https://_WebID_._PodProvider_/profile/card#me and **No permission to access this resource** error displayed.

**Comment by jaxoncreed** [comment] 2019-07-02 15:31
Duplicate of #1243

**Closed by jaxoncreed** 2019-07-02 15:31 UTC
